language: python
python:
  - 3.7
cache:
  pip: true
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run unittest
before_deploy:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry config http-basic.testpypi __token__ $TESTPYPI_TOKEN
  - poetry build
deploy:
  provider: script
  script: poetry publish -r testpypi
  skip_cleanup: true
  on:
    tags: true
    branch: master
    python: 3.7
  if: tag IS present
