language: python
python:
  - 3.7
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run unittest
before_deploy:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry config pypi-token.testpypi $TESTPYPI_TOKEN
  - poetry build
deploy:
  provider: script
  script: poetry publish -r testpypi
  skip_cleanup: true
  on:
    tags: true